feat(obstacle_stop): upd obstacle hunting
tier4/autoware.universe pull request #1068
Opened 2023-12-12 00:29 UTC by sfukuta

## Description
経路上の障害物検知した後に、障害物が移動た場合、停止線が移動した位置に対して再設定される。
その結果、停車・発車を繰り返すチャタリングが発生する問題がある。
本PRは、この問題を対策する。
※今回の対策は、OSSとして適応されている以下、PRを流用する形で適応する。
- https://github.com/autowarefoundation/autoware.universe/pull/1458
  - bug fix:https://github.com/autowarefoundation/autoware.universe/pull/1627
- https://github.com/autowarefoundation/autoware.universe/pull/2647

### 対策内容
- 対策１
  - 障害物検知による停車時に、一定時間その停止状態を維持するようにする事で、検知した障害物が移動した場合に、最初に停止した状態を維持する。
これにより、障害物の移動によるチャタリングを回避する。 
  - 停止状態を維持する時間は、`chattering_threshold`で設定する。(defalut : 0.5s)
- 対策２
  -  経路上に、複数の障害物を検知した場合、各停止線に対するチャタリングが発生しないようにする。

## Related links

https://tier4.atlassian.net/browse/AEAP-465
https://github.com/tier4/autoware_launch.x1.eve/pull/419

## Tests performed

### 機能検証
`chattering_threshold`の設定値を、default値では機能検証が難しいため、5sに変更して確認を実施。
- 障害物を経路上に設定、障害物検知し停車後に、障害物がなくなっても、即時に再発進しない事を確認済み（Psim）
- 一定時間(`chattering_threshol`で設定した時間)停止後に、再発車する事を確認済み（Psim）
- 経路上に障害物を、２つ設置し、２点間でチャタリングをしない事を確認済み（Psim）

### リグレッション評価

- 経路上に障害物がない場合に、停車しないで走行が完了する事を確認済み。(Psim）
- 経路上に障害物がある場合に、障害物検知時に、停止線で停止する事。障害物除去後に、再発車できる事を確認済み(Psim）

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2023-12-14 07:13 UTC, yn-mrse requested changes

2023-12-14 07:13 UTC, yn-mrse commented on planning/obstacle_stop_planner/src/node.cpp
> +  if (current_velocity_ptr->twist.twist.linear.x == 0) {
== 0 ではうまく合致しない可能性があるため、
fabs(current_velocity_ptr->twist.twist.linear.x) < e(誤差)
でみてあげる必要性があるのではと思います。

2023-12-15 02:14 UTC, sfukuta commented on planning/obstacle_stop_planner/src/node.cpp
> +  if (current_velocity_ptr->twist.twist.linear.x == 0) {
https://github.com/tier4/autoware.universe/pull/1068/commits/87ef309c3056dbd1805f5832bd90521721e2f8ca にて対応しました

2023-12-19 04:06 UTC, sfukuta commented
@yn-mrse 走行中の障害物検知をした場合に、停止するまで障害物停止線が消えない問題を対応 https://github.com/tier4/autoware.universe/pull/1068/commits/809b85e1a32f0b79ca2d58ccb5f95c2b9661efcb

Psimの確認内容：
- 停止中の障害物停止線が、障害物除去後に、一定時間後にクリアされる事を確認済み。
- 走行中の障害物停止線が、障害物除去後に、即時にクリアされる事を確認済み。

2023-12-19 04:59 UTC, yn-mrse approved these changes
- ソースコードを確認しましたが、Descriptionに記載の内容と合致していることから変更内容は妥当であると思われます。
- テスト内容としても、PSim及び実車にて妥当な試験が実施されており、それらをパスしているため問題ないと判断しています。

2023-12-19 05:02 UTC, merged