feat(detection_area)!: suppression of giving up stopping
tier4/autoware.universe pull request #1631
Opened 2024-11-08 09:48 UTC by yuki-takagi-66

## Description
This PR implements functionality to enable stopping when obstacles are detected within the DA (Detection Area) after passing the stop line. 

The implemented code leverages existing features from autowarefoundation to meet the requirements specified in the [documentation](https://docs.google.com/presentation/d/1_OSWKhMmRUf1QYhQGOVd9jnOLOWl8S7rGE-5VcO04zk/edit#slide=id.g315595f3e6d_0_10363).

This PR is implemented with reference to the following PRs:
- https://github.com/autowarefoundation/autoware.universe/pull/3114
- https://github.com/autowarefoundation/autoware.universe/pull/9255

### Implementation Details

The correspondence between design requirements and implementation is as follows:

|Requirement|Implementation Location|
|:--|:--|
|Add Param for margin in StopLine override judgment|https://github.com/tier4/autoware.universe/pull/1631/files#diff-eab2555cc9571b6c90cacb8122131e12d7bd9258aaf241781c4e7cf3287b7b73R61|
|Add Param for DA judgment time extension setting|https://github.com/tier4/autoware.universe/pull/1631/files#diff-eab2555cc9571b6c90cacb8122131e12d7bd9258aaf241781c4e7cf3287b7b73R62|
|When DA judgment time extension is enabled, extend DA stop judgment time until (vehicle speed > 0) is observed|https://github.com/tier4/autoware.universe/pull/1631/files#diff-45a0b8c1f68a13b18e90d3b03a96d5572006228360e908ee749b333fa7acb7e5R234-R238|
|Add margin to StopLine override judgment|https://github.com/tier4/autoware.universe/pull/1631/files#diff-45a0b8c1f68a13b18e90d3b03a96d5572006228360e908ee749b333fa7acb7e5R374-R375|

## Related links

**Parent Issue:**
- [Link](https://tier4.atlassian.net/browse/AEAP-1903?focusedCommentId=194502)
- https://github.com/tier4/autoware_launch.x1.eve/pull/511

## How was this PR tested?

Since there are no changes to the Interface*, we determined that functional testing of this DetectionAreaModule using the following Test criteria is sufficient:

- Test criteria: https://docs.google.com/presentation/d/1_OSWKhMmRUf1QYhQGOVd9jnOLOWl8S7rGE-5VcO04zk/edit#slide=id.g315595f3e6d_0_12942
- Test results: https://tier4.atlassian.net/browse/AEAP-1903?focusedCommentId=194502

I confirm that the specified tests have passed and no critical defects were found in the specified design.

*) Topic names, Msg definitions, SceneModuleInterface

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

2024-11-15 03:26 UTC, peeeechi commented
Please add the following to 'How was this PR tested?' section  
(This is to ensure that test perspectives and results can be tracked in the commit):

- Test criteria: https://docs.google.com/presentation/d/1_OSWKhMmRUf1QYhQGOVd9jnOLOWl8S7rGE-5VcO04zk/edit#slide=id.g315595f3e6d_0_12942
- Test results: https://tier4.atlassian.net/browse/AEAP-1903?focusedCommentId=194502

2024-11-15 06:13 UTC, yn-mrse requested changes
@yuki-takagi-66 
Please change the base branch from beta/v0.3.19 to beta/v0.3.20.

2024-11-15 06:15 UTC, yn-mrse requested changes
Link your internal JIRA managed tickets to maintain traceability.

2024-11-15 06:29 UTC, yn-mrse commented
@yuki-takagi-66 
![image](https://github.com/user-attachments/assets/e2a9e3cc-1ae4-492c-8b1d-a76f9ef45536)

[The basic design document](https://docs.google.com/presentation/d/1_OSWKhMmRUf1QYhQGOVd9jnOLOWl8S7rGE-5VcO04zk/edit#slide=id.g315595f3e6d_0_10363) clearly states that "please consider the detailed design," but this PR makes no mention of the detailed design.
Could you attach the detailed design to the PR?

Or, if you have decided that implementing it as per the basic design document is fine, please state that in the Description field.

2024-11-15 06:42 UTC, yn-mrse commented
Please justify all changes in the PR (show that the changes are necessary and sufficient).

In the "Description" field, clearly list the features and clarify how they correspond to the implementation.

2024-11-15 06:46 UTC, yn-mrse commented
In the "How was this PR tested?" field, please include not only the URL, but also a summary of the results and your judgement as the PR submitter as to whether the changes to this PR are appropriate.

2024-11-20 05:55 UTC, peeeechi approved these changes
LGTM!

2024-11-21 10:03 UTC, yn-mrse approved these changes

2024-11-22 00:32 UTC, peeeechi approved these changes
LGTM!

2024-11-22 00:34 UTC, merged